# Generated by Django 5.0.4 on 2024-04-10 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='menu_name')),
                ('status', models.CharField(choices=[('Empty', 'Empty'), ('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Empty', max_length=20)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu item', 'verbose_name_plural': 'Menu item'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='named_url',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='status',
            field=models.CharField(choices=[('Empty', 'Empty'), ('Allowed', 'Allowed'), ('Forbidden', 'Forbidden')], default='Empty', max_length=128, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.SlugField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='menu'),
        ),
    ]
